// Mock data for tests
import type { PlayerInput } from '../services/projectionEngine.js';

// Mock player data matching PlayerInput interface
export const mockPlayers: PlayerInput[] = [
  {
    id: 'player-1',
    name: 'LeBron James',
    team: 'LAL',
    opponent: 'GSW',
    positions: 'SF/PF',
    salary: 10500,
    projectedPoints: 52.3,
    ownership: 22.5,
    vegasImplied: 118.5,
    vegasSpread: -5.5,
    vegasTotal: 230.0,
    isHome: true,
  },
  {
    id: 'player-2',
    name: 'Stephen Curry',
    team: 'GSW',
    opponent: 'LAL',
    positions: 'PG/SG',
    salary: 10000,
    projectedPoints: 50.1,
    ownership: 28.0,
    vegasImplied: 116.0,
    vegasSpread: 5.5,
    vegasTotal: 230.0,
    isHome: false,
  },
  {
    id: 'player-3',
    name: 'Anthony Davis',
    team: 'LAL',
    opponent: 'GSW',
    positions: 'PF/C',
    salary: 9800,
    projectedPoints: 48.5,
    ownership: 18.5,
    vegasImplied: 118.5,
    vegasSpread: -5.5,
    vegasTotal: 230.0,
    isHome: true,
  },
  {
    id: 'player-4',
    name: 'Klay Thompson',
    team: 'GSW',
    opponent: 'LAL',
    positions: 'SG/SF',
    salary: 6500,
    projectedPoints: 32.5,
    ownership: 12.0,
    vegasImplied: 116.0,
    vegasSpread: 5.5,
    vegasTotal: 230.0,
    isHome: false,
  },
  {
    id: 'player-5',
    name: 'DAngelo Russell',
    team: 'LAL',
    opponent: 'GSW',
    positions: 'PG/SG',
    salary: 6000,
    projectedPoints: 30.2,
    ownership: 8.5,
    vegasImplied: 118.5,
    vegasSpread: -5.5,
    vegasTotal: 230.0,
    isHome: true,
  },
  {
    id: 'player-6',
    name: 'Kevon Looney',
    team: 'GSW',
    opponent: 'LAL',
    positions: 'C',
    salary: 4500,
    projectedPoints: 22.5,
    ownership: 5.0,
    vegasImplied: 116.0,
    vegasSpread: 5.5,
    vegasTotal: 230.0,
    isHome: false,
  },
  {
    id: 'player-7',
    name: 'Austin Reaves',
    team: 'LAL',
    opponent: 'GSW',
    positions: 'SG/SF',
    salary: 5500,
    projectedPoints: 28.0,
    ownership: 6.5,
    vegasImplied: 118.5,
    vegasSpread: -5.5,
    vegasTotal: 230.0,
    isHome: true,
  },
  {
    id: 'player-8',
    name: 'Draymond Green',
    team: 'GSW',
    opponent: 'LAL',
    positions: 'PF/C',
    salary: 5000,
    projectedPoints: 25.0,
    ownership: 7.0,
    vegasImplied: 116.0,
    vegasSpread: 5.5,
    vegasTotal: 230.0,
    isHome: false,
  },
];

// Historical game data mock
export const mockHistoricalGames = [
  {
    id: 'game-1',
    playerName: 'LeBron James',
    team: 'LAL',
    opponent: 'GSW',
    gameDate: new Date('2024-01-15'),
    season: '2024-25',
    isHome: true,
    minutes: 35.5,
    points: 28,
    rebounds: 8,
    assists: 10,
    steals: 1,
    blocks: 1,
    turnovers: 3,
    dkFantasyPoints: 55.25,
  },
  {
    id: 'game-2',
    playerName: 'LeBron James',
    team: 'LAL',
    opponent: 'BOS',
    gameDate: new Date('2024-01-13'),
    season: '2024-25',
    isHome: false,
    minutes: 38.0,
    points: 32,
    rebounds: 7,
    assists: 8,
    steals: 2,
    blocks: 0,
    turnovers: 4,
    dkFantasyPoints: 52.5,
  },
  {
    id: 'game-3',
    playerName: 'Stephen Curry',
    team: 'GSW',
    opponent: 'LAL',
    gameDate: new Date('2024-01-15'),
    season: '2024-25',
    isHome: false,
    minutes: 34.0,
    points: 35,
    rebounds: 4,
    assists: 6,
    steals: 1,
    blocks: 0,
    turnovers: 2,
    dkFantasyPoints: 48.75,
  },
];

// Team defense mock
export const mockTeamDefense = [
  {
    id: 'def-1',
    team: 'GSW',
    defEff: 112.5,
    offEff: 118.2,
    pace: 101.5,
    dvpPg: 44.8,
    dvpSg: 38.5,
    dvpSf: 40.2,
    dvpPf: 42.0,
    dvpC: 40.2,
  },
  {
    id: 'def-2',
    team: 'LAL',
    defEff: 115.2,
    offEff: 116.8,
    pace: 99.8,
    dvpPg: 42.5,
    dvpSg: 40.0,
    dvpSf: 42.5,
    dvpPf: 38.5,
    dvpC: 45.0,
  },
];

// Create mock repository functions
export function createMockHistoricalRepository() {
  return {
    getPlayerStats: vi.fn().mockResolvedValue({
      playerName: 'LeBron James',
      gamesPlayed: 45,
      seasonAvg: 52.5,
      last10Avg: 54.2,
      last5Avg: 55.0,
      last3Avg: 53.8,
      stdDev: 8.5,
      floor: 40.0,
      ceiling: 70.0,
    }),
    getGamesByDate: vi.fn().mockResolvedValue(mockHistoricalGames),
    getPlayerHistory: vi.fn().mockResolvedValue(mockHistoricalGames),
  };
}

export function createMockDefenseRepository() {
  return {
    getAllDefenseData: vi.fn().mockResolvedValue(mockTeamDefense),
    getTeamDefense: vi.fn().mockResolvedValue(mockTeamDefense[0]),
  };
}

// Import vi from vitest
import { vi } from 'vitest';
